# Generated by Django 5.1.3 on 2024-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Succulent', 'Succulent'), ('Cactus', 'Cactus'), ('Flowering', 'Flowering')], max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'A&A Plant',
                'verbose_name_plural': 'A&A Plants',
                'ordering': ['category', 'name'],
            },
        ),
    ]
