# Generated by Django 5.1.3 on 2024-11-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_a_plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'A&A Plant', 'verbose_name_plural': 'A&A Plants'},
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
