# Generated by Django 5.1.3 on 2024-11-20 10:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_a_plants', '0002_alter_plant_options_plant_description_plant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
