# Use an official Python image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the Python script
COPY AAPlants/plants_export.py /app/plants_export.py

# Install necessary dependencies
RUN pip install psycopg2-binary

# Ensure curl is available for Elasticsearch
RUN apt-get update && apt-get install -y curl

# Command to execute the script
CMD ["python3", "plants_export.py"]
