# Generated by Django 6.0.4 on 2026-04-20 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UPLCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=100)),
                ('intercom', models.CharField(blank=True, max_length=50)),
                ('sample_type', models.TextField()),
                ('solubility', models.CharField(max_length=200)),
                ('wavelength', models.CharField(max_length=50)),
                ('flow_rate', models.CharField(max_length=50)),
                ('solvent_a', models.CharField(blank=True, max_length=100)),
                ('solvent_b', models.CharField(blank=True, max_length=100)),
                ('column', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
