# Generated by Django 6.0.4 on 2026-04-21 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('step_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.RemoveField(
            model_name='uplcrequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='uplcrequest',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='uplcrequest',
            name='supervisor_comment',
        ),
        migrations.AddField(
            model_name='uplcrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplc_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='flow_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='wavelength',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lab_workflow.uplcrequest')),
            ],
            options={
                'ordering': ['step__step_order'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lab_workflow.uplcrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='uplcrequest',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_workflow.workflow'),
        ),
        migrations.AddIndex(
            model_name='uplcrequest',
            index=models.Index(fields=['status'], name='lab_workflo_status_fd0834_idx'),
        ),
        migrations.AddIndex(
            model_name='uplcrequest',
            index=models.Index(fields=['created_at'], name='lab_workflo_created_8cb196_idx'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lab_workflow.workflow'),
        ),
        migrations.AddField(
            model_name='approval',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_workflow.workflowstep'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_order')},
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('request', 'step')},
        ),
    ]
