# Generated by Django 6.0.4 on 2026-04-24 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0003_uplcrequest_approved_at_uplcrequest_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NMRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('supervisor', models.CharField(max_length=255)),
                ('thesis_title', models.CharField(max_length=500)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('lab_no', models.CharField(max_length=50)),
                ('extension_no', models.CharField(max_length=50)),
                ('sample_code', models.CharField(max_length=100)),
                ('solvent', models.CharField(max_length=100)),
                ('solubility', models.CharField(max_length=100)),
                ('molecular_weight', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('concentration', models.CharField(max_length=100)),
                ('status_h_nmr', models.CharField(max_length=255, verbose_name='Status of 1H NMR')),
                ('status_c_nmr', models.CharField(max_length=255, verbose_name='Status of 13C NMR')),
                ('cosy', models.BooleanField(default=False)),
                ('noesy', models.BooleanField(default=False)),
                ('roesy', models.BooleanField(default=False)),
                ('j_resolved', models.BooleanField(default=False)),
                ('tocsy', models.BooleanField(default=False)),
                ('dosy', models.BooleanField(default=False)),
                ('dipsi', models.BooleanField(default=False)),
                ('hsqc', models.BooleanField(default=False)),
                ('hmbc', models.BooleanField(default=False)),
                ('x_j_resolved', models.BooleanField(default=False)),
                ('hmqc_cosy', models.BooleanField(default=False)),
                ('dept_hqqc', models.BooleanField(default=False)),
                ('hsqc_tocsy', models.BooleanField(default=False)),
                ('hsqc_noesy', models.BooleanField(default=False)),
                ('data_format', models.CharField(choices=[('Hard Copy', 'Hard Copy'), ('Soft Copy', 'Soft Copy')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
