# Generated by Django 6.0.4 on 2026-04-24 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0004_nmrrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmrrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nmrrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='concentration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='data_format',
            field=models.CharField(blank=True, choices=[('Hard Copy', 'Hard Copy'), ('Soft Copy', 'Soft Copy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='extension_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='lab_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='molecular_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='solubility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='solvent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='status_c_nmr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status of 13C NMR'),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='status_h_nmr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status of 1H NMR'),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='thesis_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
