# Generated by Django 6.0.4 on 2026-04-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0005_nmrrequest_approved_at_nmrrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='request',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='nmr_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lab_workflow.nmrrequest'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='uplc_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lab_workflow.uplcrequest'),
        ),
    ]
