# Generated by Django 6.0.4 on 2026-04-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0006_remove_auditlog_request_auditlog_nmr_request_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approval',
            name='nmr_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lab_workflow.nmrrequest'),
        ),
        migrations.AddField(
            model_name='approval',
            name='uplc_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lab_workflow.uplcrequest'),
        ),
        migrations.RemoveField(
            model_name='approval',
            name='request',
        ),
    ]
