# Generated by Django 6.0.5 on 2026-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0007_alter_approval_unique_together_approval_nmr_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmrrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uplcrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
