# Generated by Django 6.0.5 on 2026-05-18 10:27

import django.utils.timezone
import lab_workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0008_nmrrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmrrequest',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Select current or future date', validators=[lab_workflow.models.validate_not_past]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uplcrequest',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Select current or future date', validators=[lab_workflow.models.validate_not_past]),
            preserve_default=False,
        ),
    ]
