# Generated by Django 6.0.5 on 2026-05-18 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0009_nmrrequest_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmrrequest',
            name='thesis_title',
            field=models.FileField(blank=True, help_text='Upload your thesis title document (PDF or Image only)', null=True, upload_to='thesis_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
