# Generated by Django 6.0.5 on 2026-05-18 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0010_alter_nmrrequest_thesis_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmrrequest',
            name='thesis_document',
            field=models.FileField(blank=True, help_text='Upload your supporting thesis title document verification scan (PDF or Image only)', null=True, upload_to='thesis_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='nmrrequest',
            name='thesis_title',
            field=models.CharField(blank=True, help_text='Enter the text title of your thesis', max_length=255, null=True),
        ),
    ]
