# Generated by Django 6.0.5 on 2026-06-02 09:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0011_nmrrequest_thesis_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uplcrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='uplcrequest',
            name='date_submitted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uplcrequest',
            name='name',
            field=models.CharField(blank=True, help_text='Applicant Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uplcrequest',
            name='precautions_ack',
            field=models.BooleanField(default=False, verbose_name='Precautions Acknowledged'),
        ),
        migrations.AddField(
            model_name='uplcrequest',
            name='thesis_document',
            field=models.FileField(blank=True, help_text='Upload your supporting thesis title document verification scan (PDF or Image only)', null=True, upload_to='uplc_thesis_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='flow_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='intercom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='solubility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='solvent_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='solvent_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='supervisor',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uplcrequest',
            name='wavelength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
