# Generated by Django 6.0.5 on 2026-06-03 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0012_remove_uplcrequest_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('catalog_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('chemical', 'Chemicals & Reagents'), ('solvent', 'Deuterated / HPLC Solvents'), ('glassware', 'Specialized Glassware'), ('consumable', 'Lab Consumables')], max_length=20)),
                ('stock_quantity', models.DecimalField(decimal_places=2, help_text='Current balance in store', max_digits=10)),
                ('unit', models.CharField(help_text='e.g., Liters, Grams, Vials, Boxes', max_length=20)),
                ('location_rack', models.CharField(blank=True, help_text='Warehouse location storage index', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SopModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instrument_id', models.CharField(help_text="Matches form array ID e.g., 'nmr' or 'uplc'", max_length=50)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='sop_docs/')),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSopCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certified_on', models.DateTimeField(auto_now_add=True)),
                ('quiz_score', models.IntegerField(help_text='Percentage grade achieved')),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_workflow.sopmodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_certs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ThesisPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('1_synopsis', 'Synopsis Submission & Defence'), ('2_coursework', 'Mandatory PhD Coursework Credit Hours'), ('3_data', 'Data Collection & Instrumentation Analysis'), ('4_pub_gate', 'First Author International Publication Gate'), ('5_writing', 'Thesis Compiling & Formatting Review'), ('6_defense', 'External Evaluation & Final Public Viva-Voce')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Not Started'), ('active', 'In Progress / Processing'), ('approved', 'Verified & Completed')], default='pending', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, help_text='Supervisor comments or requirements adjustments', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_milestones', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage'],
                'unique_together': {('student', 'stage')},
            },
        ),
    ]
