# Generated by Django 6.0.5 on 2026-06-03 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_workflow', '0013_inventoryitem_sopmodule_studentsopcertification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(choices=[('deepseek', 'DeepSeek (Thesis & Analysis Co-Pilot)'), ('mistral', 'Mistral (Instrument SOP Tutor)'), ('qwen', 'Qwen (Chemical Synthesis Oracle)')], max_length=20)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
