# Generated by Django 5.1.5 on 2025-01-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iccbs', '0002_remove_profile_profile_image_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusericcbs',
            managers=[
            ],
        ),
    ]
