# Generated by Django 5.1.5 on 2025-01-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccbs', '0003_alter_customusericcbs_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusericcbs',
            options={},
        ),
        migrations.RemoveField(
            model_name='customusericcbs',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customusericcbs',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customusericcbs',
            name='username',
        ),
        migrations.AlterField(
            model_name='customusericcbs',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customusericcbs',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customusericcbs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customusericcbs',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusericcbs',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='CustomUsericcbsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='iccbs.customusericcbs')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
