# Generated by Django 5.1.5 on 2025-01-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccbs', '0009_profile_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.AddField(
            model_name='profile',
            name='link1',
            field=models.URLField(blank=True, null=True, verbose_name='Computational Experiments-01'),
        ),
        migrations.AddField(
            model_name='profile',
            name='link2',
            field=models.URLField(blank=True, null=True, verbose_name='Computational Experiments-02'),
        ),
        migrations.AddField(
            model_name='profile',
            name='link3',
            field=models.URLField(blank=True, null=True, verbose_name='Computational Experiments-03'),
        ),
    ]
