# Generated by Django 5.1.5 on 2025-02-27 16:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iccbs', '0010_remove_profile_link_profile_link1_profile_link2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
