#version: "3.3"

services:
  jupyter:  # you can change this to whatever you want.
    container_name: TWC_Jupyter
    image: tensorflow/tensorflow:2.2.2-gpu-py3-jupyter
    volumes:
      - "./:/tf/notebooks"
    ports:
     - "3333:8888"
    environment:
      - JUPYTER_TOKEN=twc@211_sajjad  
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]

