# Generated by Django 5.2 on 2025-04-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('SNMP', 'SNMP'), ('Botany', 'Botany'), ('Infrastructure', 'Infrastructure'), ('Syslog', 'Syslog')], max_length=100, unique=True),
        ),
    ]
