# Generated by Django 5.2.8 on 2025-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('SNMP', 'SNMP'), ('Botany', 'Botany'), ('Infrastructure', 'Infrastructure'), ('Web', 'Web'), ('Syslog', 'Syslog')], max_length=100, unique=True),
        ),
    ]
