# Generated by Django 5.1.2 on 2024-10-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_course_blogpost_date_created_blogpost_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
