# Generated by Django 5.1.2 on 2024-10-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_videos_chapter_remove_videos_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
