# Generated by Django 5.1.3 on 2024-11-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_url_alter_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('SNMP', 'SNMP'), ('Botany', 'Botany')], max_length=100, unique=True),
        ),
    ]
