# Generated by Django 6.0.5 on 2026-07-10 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccountCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('HEJ', 'H.E.J.'), ('PCMD', 'PCMD'), ('LEJ', 'L.E.J.'), ('TWC', 'TWC'), ('OTHERS', 'OTHERS')], max_length=10)),
                ('doc_no', models.CharField(editable=False, max_length=50)),
                ('revision_no', models.CharField(editable=False, max_length=5)),
                ('revision_date', models.DateField(editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('lab_no', models.CharField(max_length=30)),
                ('intercom_no', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('attendance_id', models.CharField(max_length=50)),
                ('requested_email', models.EmailField(help_text='e.g. username@iccs.edu', max_length=254)),
                ('alternate_email', models.EmailField(max_length=254)),
                ('assigned_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('temporary_password', models.CharField(blank=True, max_length=128, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ITComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('HEJ', 'H.E.J.'), ('PCMD', 'PCMD'), ('LEJ', 'L.E.J.'), ('TWC', 'TWC'), ('OTHERS', 'OTHERS')], max_length=10)),
                ('doc_no', models.CharField(editable=False, max_length=50)),
                ('revision_no', models.CharField(editable=False, max_length=5)),
                ('revision_date', models.DateField(editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('FACULTY', 'Faculty'), ('STUDENT', 'Student'), ('STAFF', 'Staff')], max_length=10)),
                ('complainer_name', models.CharField(max_length=150)),
                ('supervisor_name', models.CharField(max_length=150)),
                ('lab_dept', models.CharField(max_length=100, verbose_name='Lab / Department')),
                ('intercom_no', models.CharField(max_length=30)),
                ('problem_description', models.TextField()),
                ('nature_of_problem', models.CharField(blank=True, choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Network')], max_length=15, null=True)),
                ('it_staff_remarks', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(blank=True, null=True)),
                ('service_satisfaction', models.CharField(blank=True, max_length=20, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoomLinkRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('HEJ', 'H.E.J.'), ('PCMD', 'PCMD'), ('LEJ', 'L.E.J.'), ('TWC', 'TWC'), ('OTHERS', 'OTHERS')], max_length=10)),
                ('doc_no', models.CharField(editable=False, max_length=50)),
                ('revision_no', models.CharField(editable=False, max_length=5)),
                ('revision_date', models.DateField(editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('meeting_title', models.CharField(max_length=200)),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('agenda', models.TextField(blank=True, null=True)),
                ('generated_zoom_link', models.URLField(blank=True, max_length=500, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
