# Generated by Django 5.1.3 on 2024-11-13 06:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Portfolio Project', 'verbose_name_plural': 'Portfolio Projects'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=ckeditor.fields.RichTextField(default='Default content here.'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technology',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('SNMP', 'SNMP')], max_length=30),
        ),
    ]
