# Generated by Django 5.2 on 2025-04-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='technology',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('SNMP', 'SNMP'), ('Infrastructure', 'Infrastructure'), ('Syslog', 'Syslog')], max_length=30),
        ),
    ]
