# Generated by Django 5.1.4 on 2025-01-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPlants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
