version: '3.8'

services:
  dock6:
    container_name: TWC_dock6
    build: .
    runtime: nvidia  # Add this line
    ports:
      - "7777:8888"  
    volumes:
      - ./dock6.12_source.tar.gz:/dock6/dock6.12_source.tar.gz  
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - JUPYTER_TOKEN=twc@211_huzaifa 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
