version: "3.8"

services:
  dock6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TWC_dock6
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    volumes:
      - ./notebooks:/tf/notebooks
      - ./dock6_backups:/dock6/backups
    ports:
      - "7777:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "source /opt/conda/etc/profile.d/conda.sh && \
      conda activate openmm-env && \
      jupyter notebook --ip=0.0.0.0 --port=8888 --notebook-dir=/tf/notebooks --no-browser --allow-root"